package net.gpedro.faculdade.corba.shared;


/**
* CalculadoraApp/Calculadora.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculadoraApp.idl
* Quarta-feira, 20 de Maio de 2015 00h29min10s AMT
*/

public interface Calculadora extends CalculadoraOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calculadora
