package net.gpedro.faculdade.corba.shared;


/**
* CalculadoraApp/CalculadoraOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculadoraApp.idl
* Quarta-feira, 20 de Maio de 2015 00h29min10s AMT
*/

public interface CalculadoraOperations 
{
  int somar (int n1, int n2);
  int substrair (int n1, int n2);
  int multiplicar (int n1, int n2);
  double dividir (int n1, int n2);
  void shutdown ();
} // interface CalculadoraOperations
