package net.gpedro.faculdade.corba.client;

/**
* CalculadoraApp/CalculadoraHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculadoraApp.idl
* Quarta-feira, 20 de Maio de 2015 00h28min47s AMT
*/

public final class CalculadoraHolder implements org.omg.CORBA.portable.Streamable
{
  public net.gpedro.faculdade.corba.shared.Calculadora value = null;

  public CalculadoraHolder ()
  {
  }

  public CalculadoraHolder (net.gpedro.faculdade.corba.shared.Calculadora initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = net.gpedro.faculdade.corba.client.CalculadoraHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
      net.gpedro.faculdade.corba.client.CalculadoraHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return net.gpedro.faculdade.corba.client.CalculadoraHelper.type ();
  }

}
