package net.gpedro.faculdade.corba.client;


/**
* CalculadoraApp/CalculadoraHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculadoraApp.idl
* Quarta-feira, 20 de Maio de 2015 00h28min47s AMT
*/

abstract public class CalculadoraHelper
{
  private static String  _id = "IDL:CalculadoraApp/Calculadora:1.0";

  public static void insert (org.omg.CORBA.Any a, net.gpedro.faculdade.corba.shared.Calculadora that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static net.gpedro.faculdade.corba.shared.Calculadora extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (net.gpedro.faculdade.corba.client.CalculadoraHelper.id (), "Calculadora");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static net.gpedro.faculdade.corba.shared.Calculadora read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CalculadoraStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, net.gpedro.faculdade.corba.shared.Calculadora value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static net.gpedro.faculdade.corba.shared.Calculadora narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof net.gpedro.faculdade.corba.shared.Calculadora)
      return (net.gpedro.faculdade.corba.shared.Calculadora)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      net.gpedro.faculdade.corba.client._CalculadoraStub stub = new net.gpedro.faculdade.corba.client._CalculadoraStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static net.gpedro.faculdade.corba.shared.Calculadora unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof net.gpedro.faculdade.corba.shared.Calculadora)
      return (net.gpedro.faculdade.corba.shared.Calculadora)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      net.gpedro.faculdade.corba.client._CalculadoraStub stub = new net.gpedro.faculdade.corba.client._CalculadoraStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
